package features;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class DownloadFeatures {
	private String md2Pfad;
	private static final String lView1 = "listFile";
	private static final String lView2 = "listFolder";

	public DownloadFeatures(String md2Pfad) {
		this.md2Pfad = md2Pfad;
	}

	/**
	 * In dieser Erweiterung werden die ListViews eingefügt.
	 */
	public void erweitereDownloadView() {
		try {
			String datei = "\\testprojekt.androidLollipop\\md2_app_TestprojektApp\\app\\src\\main\\res\\layout\\activity_dateidownload.xml";
			FileReader fileIn = new FileReader(md2Pfad + datei);
			BufferedReader bufIn = new BufferedReader(fileIn);

			String zeile = bufIn.readLine();

			StringBuilder builder = new StringBuilder(zeile);
			builder.insert(
					builder.indexOf(
							"<de.uni_muenster.wi.md2library.view.widgets.implementation.Md2Label android:id=\"@id/DateiDownload_ordnerLabel\""),
					"<ListView android:id=\"@+id/" + lView1
							+ "\" android:layout_width=\"wrap_content\" android:layout_height=\"wrap_content\" android:textSize=\"30dp\" android:state_selected=\"true\" android:textStyle=\"normal|italic\" />");
			builder.insert(
					builder.indexOf(
							"<de.uni_muenster.wi.md2library.view.widgets.implementation.Md2Button android:enabled=\"true\" android:id=\"@id/DateiDownload_switchView\""),
					"<ListView android:id=\"@+id/" + lView2
							+ "\" android:layout_width=\"wrap_content\" android:layout_height=\"wrap_content\" android:textSize=\"30dp\" android:state_selected=\"true\" android:textStyle=\"normal|italic\" />");

			fileIn.close();

			FileWriter fileOut = new FileWriter(md2Pfad + datei);
			fileOut.write(builder.toString());
			fileOut.close();

			String idDatei = "\\testprojekt.androidLollipop\\md2_app_TestprojektApp\\app\\src\\main\\res\\values\\ids.xml";

			String newid1 = "\t<item name=\"" + lView1 + "\" type=\"id\"/>";
			String newid2 = "\t<item name=\"" + lView2 + "\" type=\"id\"/>";

			FileReader fileIn2 = new FileReader(md2Pfad + idDatei);
			BufferedReader bufIn2 = new BufferedReader(fileIn2);

			String zeile2 = bufIn2.readLine();
			String newText = "";

			while (zeile2 != null) {

				newText += zeile2 + "\n";

				if (zeile2.equals("<resources>")) {
					newText += newid1 + "\n";
					newText += newid2 + "\n";
				}

				zeile2 = bufIn2.readLine();
			}

			fileIn2.close();

			FileWriter fileOut2 = new FileWriter(md2Pfad + idDatei);
			fileOut2.write(newText);

			fileOut2.close();

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
		}
	}
	
	public void erzeugeListenBefuellen(){
		
		try {
			String datei = "\\testprojekt.androidLollipop\\md2_app_TestprojektApp\\app\\src\\main\\java\\md2\\testprojekt\\DateiDownloadActivity.java";
			FileReader fileIn = new FileReader(md2Pfad
					+ datei);
			BufferedReader bufIn = new BufferedReader(fileIn);

			String zeile = bufIn.readLine();
			String newText = "//Autogenerated md2 Code with some extra functions\n";

			while (zeile != null) {

				newText += zeile + "\n";
				
				if (zeile.equals("package md2.testprojekt;")){
					newText += "import md2.testprojekt.md2.model.HomeFolder;\n";
					newText += "import android.widget.ListView;\n";
					newText += "import android.widget.ArrayAdapter;\n";
					newText += "import java.util.ArrayList;\n";
					newText += "import java.util.HashMap;\n";
				}
				
				if (zeile.equals("        setContentView(R.layout.activity_dateidownload);")) {
					newText += "        ListView fileListView = (ListView) findViewById(R.id." + lView1
							+ ");\n";
					newText += "        ListView folderListView = (ListView) findViewById(R.id." + lView2
							+ ");\n";
					newText += "        HomeFolder home = (HomeFolder) this.getIntent().getExtras().getSerializable(\"homeFolder\");\n";
					newText += "        HashMap<String,String> files = (HashMap) home.getFiles();\n";
					newText += "        HashMap<String,String> folders = (HashMap) home.getFolders();\n";
					newText += "        ArrayList<String> fileNames = new ArrayList<String>();\n";
					newText += "        fileNames.addAll(files.keySet());\n";
					newText += "        ArrayList<String> folderNames = new ArrayList<String>();\n";
					newText += "        folderNames.addAll(folders.keySet());\n";
					newText += "        final ArrayAdapter<String> adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, fileNames);\n";
					newText += "        fileListView.setAdapter(adapter);\n";
					newText += "        final ArrayAdapter<String> adapter2 = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, folderNames);\n";
					newText += "        folderListView.setAdapter(adapter2);\n";
				}
				
				zeile = bufIn.readLine();
			}

			fileIn.close();

			FileWriter fileOut = new FileWriter(md2Pfad
					+ datei);
			fileOut.write(newText);

			fileOut.close();

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
		}
	}
}
