package features;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class GradleBuildFeatures {

	private String md2Pfad;
	private static final String CLASSPATH = "classpath 'com.android.tools.build:gradle:3.0.1'";

	public GradleBuildFeatures(String md2Pfad) {
		this.md2Pfad = md2Pfad;
	}

	public void setClassPath() {
		try {
			FileReader fileIn = new FileReader(
					md2Pfad + "\\testprojekt.androidLollipop\\md2_app_TestprojektApp\\build.gradle");
			BufferedReader bufIn = new BufferedReader(fileIn);

			String zeile = bufIn.readLine();
			String newText = "//Autogenerated md2 Code with some extra functions\n";

			int auslassen = 0;

			while (zeile != null) {
				if (auslassen == 0) {
					newText += zeile + "\n";
				} else {
					auslassen--;
				}
				if (zeile.equals("\tdependencies {")) {
					newText += "\t\t" + CLASSPATH + "\n";
					newText += "\t}\n";
					auslassen = 2;
				}
				zeile = bufIn.readLine();
			}

			fileIn.close();

			FileWriter fileOut = new FileWriter(
					md2Pfad + "\\testprojekt.androidLollipop\\md2_app_TestprojektApp\\build.gradle");
			fileOut.write(newText);

			fileOut.close();

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
		}
	}
}
