package features;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class StartViewFeatures {
	private String md2Pfad;

	public StartViewFeatures(String md2Pfad) {
		this.md2Pfad = md2Pfad;
	}

	public void createCloseFunction() {
		try {
			FileReader fileIn = new FileReader(md2Pfad
					+ "\\testprojekt.androidLollipop\\md2_app_TestprojektApp\\app\\src\\main\\java\\md2\\testprojekt\\StartActivity.java");
			BufferedReader bufIn = new BufferedReader(fileIn);

			String zeile = bufIn.readLine();
			String newText = "//Autogenerated md2 Code with some extra functions\n";

			int auslassen = 0;

			while (zeile != null) {
				if (auslassen == 0) {
					newText += zeile + "\n";
				} else {
					auslassen--;
				}
				if (zeile.equals("\tpublic void onBackPressed() {")) {
					newText += "\t\tIntent intent = new Intent(Intent.ACTION_MAIN);\n";
					newText += "\t\tintent.addCategory(Intent.CATEGORY_HOME);\n";
					newText += "\t\tintent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);\n";
					newText += "\t\tstartActivity(intent);\n";
					newText += "\t\tfinish();\n";
					newText += "\t\tSystem.exit(0);\n";
					newText += "\t}\n";
					auslassen = 2;
				}
				zeile = bufIn.readLine();
			}

			fileIn.close();

			FileWriter fileOut = new FileWriter(md2Pfad
					+ "\\testprojekt.androidLollipop\\md2_app_TestprojektApp\\app\\src\\main\\java\\md2\\testprojekt\\StartActivity.java");
			fileOut.write(newText);

			fileOut.close();

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally {
		}
	}
}
